### ISSUE TITLE
Failing CLI commands from opentsdb-bigtable setup (2.4)

### ISSUE THREAD

**Issue by nimitnagpal** [GoogleCloudPlatform/opentsdb-bigtable#17]
I am trying to fix some orphaned data as per http://opentsdb.net/docs/build/html/user_guide/cli/fsck.html

However, I am facing `unknown --scan` error while running this from CLI 

root@opentsdb-read-854b77c77c-2l695:/usr/local/bin# tsdb fsck
Running OpenTSDB with Bigtable support
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/share/opentsdb/lib/asyncbigtable-0.3.1-20170903.031804-2-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/share/opentsdb/lib/logback-classic-1.0.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
log4j:WARN No appenders could be found for logger (net.opentsdb.utils.Config).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.lang.IllegalArgumentException: Unknown option --sync
	at net.opentsdb.tools.ArgP.has(ArgP.java:213)
	at net.opentsdb.tools.FsckOptions.<init>(FsckOptions.java:57)
	at net.opentsdb.tools.Fsck.main(Fsck.java:1282)

**Comment by varundhussa** [comment]
Updating the asyncbigtable to 0.4.2 in building OpenTSDB should fix this
